env:
  global:
    # The deploy target uses TRAVIS_TAG.
    - TRAVIS_TAG=weekly

sudo: required
before_script:
  - sudo apt-get update
  # Need to install 32-bit libraries so that we can run windres while
  # building Windows installers.
  - sudo apt-get install lib32z1 lib32ncurses5
  
script:
        ./build-kepler.sh

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file:
      - $HOME/build/icyphy/finished-kepler-installers/linux/Kepler-2.6.0.1-linux.tar.gz
      - $HOME/build/icyphy/finished-kepler-installers/windows/Kepler-2.6.0.1-win.exe
    on:
      tags: true
    overwrite: true
    skip_cleanup: true    
    verbose: true
