env:
  global:
    # The deploy target uses TRAVIS_TAG.
    - TRAVIS_TAG=weekly

matrix:
  include:
    - env: JDK='Oracle JDK 8'
      jdk: oraclejdk8
    - env: JDK='Oracle JDK 10'
      install: . ./install-jdk.sh -F 10 -L BCL

sudo: required

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

before_script:
  - sudo apt-get update
  # Need to install 32-bit libraries so that we can run windres while
  # building Windows installers.
  - sudo apt-get install lib32z1 lib32ncurses5
  
script:
        ./build-kepler.sh

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file:
      - $HOME/build/icyphy/finished-kepler-installers/linux/Kepler-2.6.0.1-linux.tar.gz
      - $HOME/build/icyphy/finished-kepler-installers/windows/Kepler-2.6.0.1-win.exe
    on:
      tags: true
      condition: $JDK = 'Oracle JDK 8'
    overwrite: true
    skip_cleanup: true    
    verbose: true

# See https://docs.travis-ci.com/user/notifications/
# notifications:
#  email:
#    recipients:
#      - cxh@eecs.berkeley.edu
#    on_success: always # default: change
#    on_failure: always # default: always
