dist: focal

env:
  global:
    # The deploy target uses TRAVIS_TAG.
    - TRAVIS_TAG=weekly

matrix:
  include:
    - env: JDK='Oracle JDK 9'
      jdk: oraclejdk9
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    - env: JDK='Oracle OpenJDK 11'
      jdk: openjdk11
      before_install:
        # Fix "No PSK available. Unable to resume" in jdk 11.0.2
        # See https://github.com/icyphy/kepler-build/issues/1
        # and https://stackoverflow.com/questions/52574050/javax-net-ssl-sslexception-no-psk-available-unable-to-resume
        # Figuring out how to upgrade to jdk 11.0.3 or later might also work.
        - ant -version
        - echo ${JAVA_HOME}
        - ls ${JAVA_HOME}
        - ls ${JAVA_HOME}/conf
        - ls ${JAVA_HOME}/conf/security
        - ls -l ${JAVA_HOME}/conf/security/java.security
        - cat ${JAVA_HOME}/conf/security/java.security
        - sed 's/jdk.tls.disabledAlgorithms=/jdk.tls.disabledAlgorithms=TLSv1.3, /' ${JAVA_HOME}/conf/security/java.security > /tmp/java.security.new
        - diff /tmp/java.security.new ${JAVA_HOME}/conf/security/java.security || true
        - sudo mv /tmp/java.security.new ${JAVA_HOME}/conf/security/java.security
        - ls -l ${JAVA_HOME}/conf/security/java.security
        - grep jdk.tls.disabledAlgorithms= ${JAVA_HOME}/conf/security/java.security || true
    - env: JDK='Oracle OpenJDK 12'
      jdk: openjdk12
    # Building under JDK 13 fails because the old doclet interface was removed.  See https://github.com/icyphy/kepler-build/issues/3  
    # - env: JDK='Oracle OpenJDK 13'
    #   jdk: openjdk13
sudo: required

before_script:
  - sudo apt-get update
  # Need to install 32-bit libraries so that we can run windres while
  # building Windows installers.
  - sudo add-apt-repository universe
  # Under Ubuntu 20.x (focal) change lib32ncurses5 to 6
  - sudo apt-get install lib32z1 lib32ncurses6 ant
  # Fix a cert problem, see https://stackoverflow.com/questions/69387175/git-for-windows-ssl-certificate-problem-certificate-has-expired
  # Ubuntu 20.x focal: this file does not exist
  - sudo ls -l /usr/share/ca-certificates/mozilla/DST_Root_CA_X3.crt || true
  - sudo rm -f /usr/share/ca-certificates/mozilla/DST_Root_CA_X3.crt || true
  - sudo update-ca-certificates || true  
script:
  # Echo status messages so that Travis knows we are alive.
  # If you need to get status about available memory, insert "free -m; top -b -n 1 -o %MEM | head -20 " inside the loop.
  - while sleep 1m; do echo "=====[ $SECONDS seconds still running ]====="; free -m; done &

  - echo "About to call ./build-kepler.sh at $SECONDS seconds."

  - ./build-kepler.sh

  - echo "About to call ./build-kepler.sh at $SECONDS seconds."

  # Killing background sleep loop.
  - kill %1

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file:
      - $HOME/build/icyphy/finished-kepler-installers/linux/Kepler-2.6.0.1-linux.tar.gz
      - $HOME/build/icyphy/finished-kepler-installers/windows/Kepler-2.6.0.1-win.exe
    on:
      tags: true
      condition: $JDK = 'Oracle JDK 9'
    overwrite: true
    skip_cleanup: true    
    verbose: true

# See https://docs.travis-ci.com/user/notifications/
notifications:
 email:
   recipients:
     - jones@nceas.ucsb.edu
     - danielcrawl@gmail.com
     - michal.owsiak@man.poznan.pl
     - cxbrooks@gmail.com
   on_success: always # default: change
   on_failure: always # default: always
